### ISSUE TITLE
Error when running on ios

### ISSUE THREAD

**Issue by tudosxxx** [rwscode/dart_castscreen#1]
flutter: SocketException: Send failed (OS Error: No route to host, errno = 65), address = ::, port = 1900
flutter: #0  _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2582:15)
#2      CastScreen._search (package:castscreen/src/core/core.dart:229:16)
#3      CastScreen._discover (package:castscreen/src/core/core.dart:62:5)
<asynchronous suspension>
#4      CastScreen.discoverDevice (package:castscreen/src/core/core.dart:45:5)
<asynchronous suspension>
#5      Util.search (package:demo/util.dart:124:5)
<asynchronous suspension>

The same method code runs without problem on Android. An error is reported on the ios side

**Comment by billcoding** [comment]
Thank you for submitting the issue.
This problem seems to be a problem with your network environment.

**Comment by billcoding** [comment]
@tudosxxx PLS check your network env.
