### ISSUE TITLE
iOS 扫描设备报错：  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 1900

### ISSUE THREAD

**Issue by Mauiie** [rwscode/dart_castscreen#4]
iOS 扫描设备报错：  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 1900

Flutter 版本 3.16.9

我试了Android 是正常的，iOS搜索设备就报错，试着添加了一些权限之类的也没生效

**Comment by billcoding** [comment]
非常感谢你的反馈。
你可以提供下，示例代码吗？
我已经在iOS上测试过，是可以搜索到设备的。
下面是iOS模拟器，运行example效果。
![image](https://github.com/user-attachments/assets/a1e51add-72f3-4422-bd5b-e7df6be82087)
